version: "3"

includes:
  python-client:
    taskfile: projects/python-client
    dir: projects/python-client

  docs:
    taskfile: docs
    dir: docs

  web-components:
    taskfile: projects/web-components
    dir: projects/web-components

tasks:
  link-local-report:
    desc: Link the local-report artifacts into the python-client codebase (for Report.save)
    cmds:
      - |
        ln -svf '../../../../../web-components/dist/local-report/local-report-base.{css,js}' "projects/python-client/src/datapane/resources/local_report/"
        ln -svf '../../../../../web-components/dist/report' "projects/python-client/src/datapane/resources/local_report/report"
        ln -svf '../../../../../web-components/dist/vue.esm-browser.prod.js' "projects/python-client/src/datapane/resources/local_report/vue.esm-browser.prod.js"
