version: "3"

includes:
  python-client:
    taskfile: projects/python-client
    dir: projects/python-client

  docs:
    taskfile: docs
    dir: docs

  web-components:
    taskfile: projects/web-components
    dir: projects/web-components

tasks:
  link-local-report:
    desc: Link the local-report artifacts into the python-client codebase (for Report.save)
    cmds:
      - |
        ln -svf '../../../../../web-components/dist/local-report/local-report-base.js' "projects/python-client/src/datapane/resources/local_report/local-report-base.js"
        ln -svf '../../../../../web-components/dist/local-report/local-report-base.css' "projects/python-client/src/datapane/resources/local_report/local-report-base.css"
        ln -svf '../../../../../../../web-components/dist/report' "projects/python-client/src/datapane/resources/local_report/served_template/dist/report"
        ln -svf '../../../../../../../../web-components/dist/base/DPClipboard.js' "projects/python-client/src/datapane/resources/local_report/served_template/dist/base/DPClipboard.js"
        ln -svf '../../../../../../../../web-components/dist/base/code-block.es.js' "projects/python-client/src/datapane/resources/local_report/served_template/dist/base/code-block.es.js"
