module.exports = {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {},
  },
  plugins: [],
  content: [
    // FE files
    "./src/**/*.html",
    "./src/**/*.tsx",
    // BE files
    "../dp-server/src/dp/apps/dp_core/templates/**/*.html",
    "../dp-server/src/dp/apps/dp_marketing/templates/**/*.html",
    "../dp-server/src/dp/apps/dp_comments/templates/**/*.html",
    "../dp-server/src/dp/apps/dp_org/templates/**/*.html",
    "../dp-server/src/dp/apps/dp_public/templates/**/*.html",
    "../dp-server/templates/**/*.html",
  ],
  safelist: [
    /bp3-.*/,
    /DayPicker.*/,
    /grid-cols-.*/,
    /grid-rows-.*/,
    /grid-flow-.*/,
    /dp-btn-.*/,
    "text-teal-400",
    "text-orange-400",
    "text-blue-400",
    "text-green-400",
    "text-indigo-400",
    "text-red-400",
    "mb-3",
    "bg-green-100",
    "bg-green-800",
    "bg-red-100",
    "bg-red-800",
    "max-w-screen-xl",
    "max-w-3xl",
    "max-w-full",
    "w-full",
    "h-full",
    "max-w-none",
    "absolute",
    "top-0",
    "left-0",
  ],
};
