version: "3"

includes:

env:

tasks:
  install:
    desc: "Install dependencies ready for development on the codebase"
    run: once
    cmds:
      - cmd: git config filter.clear-notebook-output.clean "poetry run jupyter nbconvert --ClearOutputPreprocessor.enabled=True --ClearMetadataPreprocessor.enabled=True --ClearMetadataPreprocessor.preserve_cell_metadata_mask tags --to=notebook --stdin --stdout --log-level=ERROR"
      - cmd: poetry install

  test:
    desc: "Run self-contained tests"

  build:
    desc: "Build a package ready for a deploy"
    cmds:
      - cmd: poetry run ./nbbuild.sh
      - cmd: poetry run mkdocs build

  serve:
    desc: "Serve the site locally"
    cmds:
      - cmd: poetry run mkdocs serve

  deploy:
    desc: "Deploy the package"
    cmds:
      # wrangler pages doesn't support a config file yet
      - cmd: wrangler pages publish --project-name datapane-docs site
