version: "3"

includes:

env:

tasks:
  install:
    desc: "Install dependencies ready for development on the codebase"
    run: once
    cmds:
      - cmd: git config filter.clear-notebook-output.clean "./public-docs/clear-notebook-output.sh"
      - cmd: poetry install

  test:
    desc: "Run self-contained tests"

  build:
    desc: "Build a package ready for a deploy"
    env:
      DATAPANE_CDN_BASE: '{{ .DATAPANE_CDN_BASE | default "" }}'
    cmds:
      - cmd: poetry run ./nbbuild.sh
      - cmd: poetry run mkdocs build

  build-docs-only:
    desc: "Locally build the docs only (don't run notebooks)"
    env:
      DATAPANE_CDN_BASE: '{{ .DATAPANE_CDN_BASE | default "" }}'
    cmds:
      - cmd: poetry run mkdocs build

  build:inline-statics:
    desc: "Build a package ready for a deploy, with report statics loaded into the build"
    cmds:
      - cmd: ln -s ../../web-components/dist docs/_report-statics
      - defer: rm docs/_report-statics
      - task: build
        vars:
          DATAPANE_CDN_BASE: /_report-statics

  serve:
    desc: "Serve the site locally"
    cmds:
      - cmd: poetry run mkdocs serve

  serve:inline-statics:
    desc: "Serve the site locally, with report statics loaded into the build"
    cmds:
      - cmd: ln -s ../../web-components/dist docs/_report-statics
      - defer: rm docs/_report-statics
      - task: serve
        vars:
          DATAPANE_CDN_BASE: /_report-statics

  deploy:
    desc: "Deploy the package"
    cmds:
      # wrangler pages doesn't support a config file yet
      - cmd: wrangler pages publish --project-name datapane-docs site
