name: Update API Docs

on:
  # Publish the API Docs whenever there's a release
  push:
    tags:
      - v*

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          fetch-depth: 5
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: set pip cache dir
        run: python -c 'from pip._internal.locations import USER_CACHE_DIR; print(f"PIP_DIR={USER_CACHE_DIR}")' >> ${GITHUB_ENV}
      - name: set python version
        run: python -c 'import sys; print(f"PYTHON_VERSION={sys.hexversion}")' >> ${GITHUB_ENV}
      # TODO - cache the poetry pypi cache dir? (tho as we cache the venv is it needed?)
      - name: Cache .venv
        uses: actions/cache@v2
        with:
          path: projects/python-client/.venv
          key: datapane-venv-v1-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('projects/python-client/poetry.lock') }}
          restore-keys: datapane-venv-v1-${{ runner.os }}-${{ env.PYTHON_VERSION }}-
      - name: Cache pip dir (${{ env.PIP_DIR }})
        uses: actions/cache@v2
        with:
          path: ${{ env.PIP_DIR }}
          key: datapane-pip-${{ runner.os }}-${{ env.PYTHON_VERSION }}
          restore-keys: datapane-pip-${{ runner.os }}-
      - name: Build Docs
        working-directory: ./projects/python-client/
        run: |
          pip install 'poetry~=1.2.0'
          poetry config virtualenvs.in-project true
          poetry install
          # --config 'lunr_search={"fuzziness": 1, "index_docstrings": True}'
          poetry run pdoc --html --config show_source_code=False --config list_class_variables_in_index=False --config sort_identifiers=False --config 'google_analytics="UA-167952366-2"' --config show_inherited_members=True -f --output-dir ./docs1 datapane.client.api
          # HACK for lunr js sarch not working fully - see https://github.com/pdoc3/pdoc/issues/250
          # mv -v docs1/datapane/client/api/* docs
          mkdir ./docs
          mv -t ./docs ./docs1/datapane/client/api/*
      - name: Deploy Docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./projects/python-client/docs
          # force_orphan: true
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'
